name: Build

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Zip
        run: zip -r "Vanilla-Raytraced.${{ steps.latest_release_info.outputs.tag_name }}.mcpack" "Vanilla Raytraced"
      
      - name: Upload to Github
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: Vanilla-Raytraced.${{ steps.latest_release_info.outputs.tag_name }}.mcpack
          asset_name:  Vanilla-Raytraced.${{ steps.latest_release_info.outputs.tag_name }}.mcpack
          asset_content_type: application/zip
